### ISSUE TITLE
Server error

### ISSUE THREAD

**Issue by IscoGamer503** [Zerthick/CommandSkript#2]
Server thread/ERROR [Sponge]: Could not pass FMLInitializationEvent to Plugin{id=commandcore, name=CommandCore, version=0.2.0, description=Core Library for CommandSkript Plugins, authors=[Zerthick], source=/mods/CommandCore-v0.2.0.jar}
23.01 20:55:08 [Server] INFO java.lang.NoClassDefFoundError: io/github/zerthick/commandskript/CommandSkriptLexer
23.01 20:55:08 [Server] INFO at io.github.zerthick.commandcore.skript.Skript.<init>(Skript.java:45) ~[Skript.class:?]
23.01 20:55:08 [Server] INFO at io.github.zerthick.commandcore.CommandCore$$Lambda$593/1177297596.apply(Unknown Source) ~[?:?]

**Comment by Zerthick** [comment]
Moving discussion to https://github.com/Zerthick/CommandCore/issues/2
